[build]
builder = "nixpacks"

[deploy]
startCommand = "mkdir -p /app/storage/app/public /app/storage/app/livewire-tmp && php artisan storage:link && (test -f /app/storage/app/database.sqlite || touch /app/storage/app/database.sqlite) && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
